language: python
python: 2.7
env:
- TOX_ENV=py35
- TOX_ENV=flake8
install:
- pip install tox
script:
- tox -e $TOX_ENV
notifications:
  irc: chat.freenode.net#python-scotland
  on_success: change
  on_failure: change
deploy:
  provider: heroku
  api_key:
    secure: Kwq6mfjOlaIeh2gK1rHbWCaFydx9NLnfC+OASe477Em+WUWVuOhUF1odxZqzczkEEjkwcVCdHqfBb86ajX7WKe80mWzujDTRavisbCbDe1BrcofT7udaclfbFjh4bjECaEzxXkVag+mMFpJm6eiBZFYjhrcVS9rUR52cOCesgcc=
  on:
    repo: python-glasgow/pythonglasgow
    condition: "$TOXENV = py35"